// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUXIzaDgTvgA5X2awzRqER0dE-PuNasvs',
    appId: '1:199629108280:web:76c41c1a70bc1a8c4622cd',
    messagingSenderId: '199629108280',
    projectId: 'points-jordan',
    authDomain: 'points-jordan.firebaseapp.com',
    storageBucket: 'points-jordan.firebasestorage.app',
    measurementId: 'G-6L3BK4MM6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_JWO_J9hn0yZdNKCLlyEVox883a2dxjk',
    appId: '1:199629108280:android:343ee6b1c5effc304622cd',
    messagingSenderId: '199629108280',
    projectId: 'points-jordan',
    storageBucket: 'points-jordan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeYYrj_vxywavPWoYolpPZoLsiacXPXrg',
    appId: '1:199629108280:ios:7401675113c991444622cd',
    messagingSenderId: '199629108280',
    projectId: 'points-jordan',
    storageBucket: 'points-jordan.firebasestorage.app',
    iosClientId: '199629108280-v9ih5036g2p9lvlv5ccm9dnjkjeh4g3p.apps.googleusercontent.com',
    iosBundleId: 'com.papayatrading.points',
  );

}